services:
# ----------------------------------------------
# EXPOSE FILES FROM ./assets 
# ----------------------------------------------
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./assets/:/usr/share/nginx/static/

  ftpd:
    image: delfer/alpine-ftp-server
    volumes:
      - ./assets/:/ftp/alpineftp/
  
  smb:
    image: dperson/samba
    ports:
      - 139:139
      - 445:445
    environment:
      USER: "lucas;pass"
      SHARE: "public;/share"
    volumes:
      - ./assets/:/share

# ----------------------------------------------
# EXPOSE TCP BIND SHELL (mimic compromised host)
# ----------------------------------------------
  bindshell:
    image: busybox
    command: ["/bin/sh", "-c", "/bin/nc -lvnp 1337 -e /bin/sh"]

# ----------------------------------------------
# CLIENT TO CONNECT TO SERVICES ABOVE
# ----------------------------------------------
  client:
    image: alpine
    command: ["/bin/sh", "/scripts/entrypoint.sh"]
    volumes:
      - ./client/:/scripts

# ----------------------------------------------
# CAPTURE PACKETS ON COMPOSE STACK NETWORK
# ----------------------------------------------
  # capture:
  #   image: alpine
  #   command: ["/bin/sh", "-c", "apk update && apk add tcpdump && tcpdump -w /capture/$(date +'%Y-%m-%d_%H_%M').pcap"]
  #   volumes:
  #     - ./samples/:/capture
