import sys

if len(sys.argv) != 2:
    print("Usage: python generator.py <IP_GW>")
    sys.exit(1)

IP_GW = sys.argv[1]
RULESET_NAME = "mssis.rules"

# rules templates
RULES = [
    # detect unknown HTTP User-Agent
    f"""alert http {IP_GW} any -> any any (msg:"MSSIS Connection from unknown HTTP User-Agent"; \\
        http.user_agent; dataset:set,ua, type string, state {IP_GW.replace('.','_')}_ua.txt; \\
        sid:1; rev:1;)""",
    # detect unknown TLS JA4
    f"""alert tls {IP_GW} any -> any any (msg:"MSSIS Connection with unknown TLS JA4"; \\
        ja4.hash; dataset:set,ja4, type string, state {IP_GW.replace('.','_')}_ja4.txt; \\
        sid:2; rev:1;)""",
    # detect unknown HTTP Host
    f"""alert http {IP_GW} any -> any any (msg:"MSSIS Connection with unknown HTTP Host"; \\
        http.host; dataset:set,host, type string, state {IP_GW.replace('.','_')}_host_sni.txt; \\
        sid:3; rev:1;)""",
    # detect unknown TLS SNI
    f"""alert tls {IP_GW} any -> any any (msg:"MSSIS Connection with unknown TLS SNI"; \\
        tls.sni; dataset:set,sni, type string, state {IP_GW.replace('.', '_')}_host_sni.txt; \\
        sid:4; rev:1;)""",
    # detect dest IP on internet when proto is not HTTP or TLS
    f"""pass http {IP_GW} any -> any any (msg:"MSSIS pass HTTP"; \\
        sid:5; rev:1;)""",
    f"""pass tls {IP_GW} any -> any any (msg:"MSSIS pass TLS"; \\
        sid:6; rev:1;)""",
    f"""alert ip {IP_GW} any -> $EXTERNAL_NET any (msg:"MSSIS Connection to unknown "; \\
        ip.dst; dataset:set,ip, type ipv4, state {IP_GW.replace('.', '_')}_external_ips_not_http_tls.txt; \\
        sid:7; rev:1;)"""
]

# dump rules to file
with open(RULESET_NAME, "w") as f:
    f.write("# MSSIS autogenerated rules\n")
    for rule in RULES:
        f.write(rule + "\n")
